site_name: ELIXIR Training Lesson
nav:
    - About: index.md
    - Course Content:
      - "Preface": chapters/00_Preface.md
      - "Searching in TeSS": chapters/chapter_01.md
      - "Manual registration of events, material and a provider": chapters/chapter_02.md
      - "Integrating TeSS widgets on your web site": chapters/chapter_03.md
      - "Automatic ingestion of events or material via Bioschemas": chapters/chapter_04.md
      - "References": chapters/references.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-TeSS
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-TeSS
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards


extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

